baseURL = "https://bloxxyyy.github.io"
languageCode = "en-US"
title = "bloxxyyy's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "bloxxyyy"
  github = "bloxxyyy"
  description = "Created as a creative outlet."
  rss = true
  location = "The Netherlands"
  headerIcon = "https://bloxxyyy.github.io/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]